image: python:3.12

stages:
  - build
  - test
  - deploy

variables:
  DJANGO_SETTINGS_MODULE: "config.settings"
  DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/mydatabase"
  ALLOWED_HOSTS: "$ALLOWED_HOSTS"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py collectstatic --noinput

test:
  stage: test
  script:
    - python manage.py pytest

deploy:
  stage: deploy
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y sshpass
    - sshpass ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd $ABSOLUTE_PATH_PROJECT && git pull && source $SOURCE_PATH_ACTIVATE && pip install -r requirements.txt && python manage.py migrate && systemctl restart config'
